language: node_js
node_js:
- '0.10'
- '4.2'
services:
- elasticsearch
env:
  - SKIP_TRANSCODING=1 SM_TEST_JS=1 DEBUG=sm:modes:standalone,sm:util:stream_listener,sm:slave:stream CXX=g++-4.8
sudo: false
notifications:
  slack:
    secure: c2GoWrff8tjrQmyhYRA+kv1FKzlFLpASo5BrHBSzrvPSFB883Z/hcfR7qqQ3kCl7OV8Q+dYnYFchpV6hO99NTMs5nSd+ob9CxXAlBvVGuYWJVMmcmgt9liqtnFB5aZvQbYkXOkmpMofgSNQmUsWoqGJ/WwGmG00YuBjivDMXQxw=
branches:
  only:
    - master
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
